/**
 * skillVideos.js — curated short-clip videos for the player-development knowledge layer.
 *
 * Keyed by skillGraph.js SKILL id. One reviewed YouTube clip per skill (trusted trainer, or a
 * clip whose title explicitly teaches the skill; all <= ~4 min). Generated by NextPlay's gated
 * enrichment pipeline (enrich-dev-skills.mjs -> human review -> import). Data only — no UI here.
 *
 * Consume from a skill card:  import { SKILL_VIDEOS } from "./skillVideos";
 *                             const v = SKILL_VIDEOS[skill.id];   // may be undefined
 *
 * 58 of ~70 leaf skills covered. Missing ones (rebounding micro-cues, a few handle
 * sub-moves) had no distinct clip in search and are left out on purpose rather than mislabeled.
 */
export const SKILL_VIDEOS = {
  // ── defense ──
  closeout:              { videoId: "CS6x2CF2pKI", title: "Closeout Drill#basketball #ballislife #physicaltherapy #defense", channel: "Sulham Athletics", seconds: 8, source: "youtube" },
  containment:           { videoId: "voDcaAlaHDU", title: "Youth Basketball Drills: Foster's 1v1", channel: "Brian McCormick", seconds: 9, source: "youtube", trusted: true },
  slide:                 { videoId: "rOpVN2Lu654", title: "Improve Your Lateral Quickness and Power | Basketball Drills", channel: "KP Sports Performance", seconds: 18, source: "youtube" },
  recover_xout:          { videoId: "dCEV0xnIlIM", title: "Basketball Defensive Technique: Three Player Rotation on an Defensive X-Out", channel: "Basketball Immersion", seconds: 58, source: "youtube", trusted: true },
  contest:               { videoId: "wAN8lPIQqco", title: "How To Contest Shots Without Fouls In Basketball", channel: "Basketball Coach Allen", seconds: 13, source: "youtube" },

  // ── finishing ──
  euro:                  { videoId: "h_qPJ5VOvis", title: "How to Execute the EURO STEP in Basketball the RIGHT WAY! ✅", channel: "ILoveBasketballTV", seconds: 13, source: "youtube", trusted: true },
  layup:                 { videoId: "sb-CUR8PB_0", title: "Layup Drills For Beginners ✅", channel: "Get Handles Basketball", seconds: 18, source: "youtube", trusted: true },
  pro_hop:               { videoId: "Z_O3ERIdWl4", title: "PRO HOP #shorts", channel: "Clutch & Culture", seconds: 9, source: "youtube" },
  reverse:               { videoId: "OUO94jaAvz4", title: "How To Reverse Layups For Beginners ✅ Basketball Basics", channel: "Get Handles Basketball", seconds: 24, source: "youtube", trusted: true },
  speed_gather:          { videoId: "Qvj-cfs67AA", title: "STOP Missing Full Speed Layups #gooddrill", channel: "Good Drill", seconds: 37, source: "youtube" },
  scoop:                 { videoId: "r7OGMVmkNb0", title: "OVERHAND & UNDERHAND LAYUPS | BASKETBALL SKILL BREAKDOWN", channel: "FIBA Basketball", seconds: 115, source: "youtube" },

  // ── footwork ──
  front_pivot_skill:     { videoId: "jEAvb1gcbc0", title: "WORK ON YOUR PIVOT FOOTWORK!!!!", channel: "HoopStudy", seconds: 33, source: "youtube", trusted: true },
  jab_go:                { videoId: "imXZsA4nYb4", title: "Kyrie Setup Jabs 🥊", channel: "Get Handles Basketball", seconds: 18, source: "youtube", trusted: true },
  jump_stop_skill:       { videoId: "p2Byoij6NNA", title: "Jump 🏀 Stop Passing & Pivoting Drill", channel: "Cramer Basketball", seconds: 14, source: "youtube" },
  reverse_pivot_skill:   { videoId: "MV2N0tjfdbo", title: "Basketball Drills for Beginners | Reverse Pivot Attack Drill", channel: "ShotMechanics", seconds: 115, source: "youtube", trusted: true },
  rip_through:           { videoId: "iwEVz8yxdgI", title: "The DIRTY Post Move You’re NOT Using (But Should Be) the RIP DROP SPIN", channel: "Coach Ducharme (Coach Chrispect)", seconds: 7, source: "youtube" },
  step_through:          { videoId: "J-sGu1b3zcg", title: "3 DEADLY Variations of the Step-Through Move in Basketball! 💀", channel: "ILoveBasketballTV", seconds: 36, source: "youtube", trusted: true },

  // ── handles ──
  behind:                { videoId: "rYfD6c9N39o", title: "Get A SHIFTY Behind Back (Drills)", channel: "Get Handles Basketball", seconds: 18, source: "youtube", trusted: true },
  between:               { videoId: "bAgzuO4W4DQ", title: "EASIEST Way to Dribble Between the Legs! FULL TUTORIAL!", channel: "ILoveBasketballTV", seconds: 36, source: "youtube", trusted: true },
  cross_behind:          { videoId: "XvQFAjvRtwI", title: "Behind Back MISTAKE ❌", channel: "Get Handles Basketball", seconds: 23, source: "youtube", trusted: true },
  cross:                 { videoId: "e4XvisoxHo0", title: "KEYS TO A BETTER CROSSOVER!!!!!", channel: "HoopStudy", seconds: 21, source: "youtube", trusted: true },
  half_spin:             { videoId: "QcxcEpDTrCM", title: "Spin Move HACK ☠️", channel: "Get Handles Basketball", seconds: 44, source: "youtube", trusted: true },
  hang_hesi_cross:       { videoId: "qpnJm5_lD30", title: "5 Hesi’s That Get Defenders Jumping Like a Pop Tart 🔥", channel: "PJFPerformance", seconds: 27, source: "youtube", trusted: true },
  hang:                  { videoId: "9_gZdymG5qc", title: "The Hang Dribble Secret That Makes You SHIFTY 👀", channel: "ILoveBasketballTV", seconds: 61, source: "youtube", trusted: true },
  hesitation:            { videoId: "TxyQaGXPJ3U", title: "WORK ON YOUR HESITATION MOVES", channel: "HoopStudy", seconds: 31, source: "youtube", trusted: true },
  in_out:                { videoId: "dF61fgRPa3g", title: "it's Dribbling Basic.「In And Out」.basketball skill. #animation #basketballtraining", channel: "KaKaBasketball", seconds: 10, source: "youtube" },
  pound:                 { videoId: "ZFUzXbAMcgU", title: "High Pound Dribbling Drill #ballhandling", channel: "No Excuse Produce ", seconds: 10, source: "youtube" },
  pullback:              { videoId: "Xa3axxbIL5U", title: "Check out this to improve your Pullback Dribble", channel: "Billy Clapper Basketball", seconds: 9, source: "youtube" },
  push_cross:            { videoId: "TwsnggwSBfc", title: "✅ How To Cross Jab In 10 Seconds ⏱️", channel: "Get Handles Basketball", seconds: 9, source: "youtube", trusted: true },
  retreat:               { videoId: "GV8tuux5R9Q", title: "Retreat Dribble", channel: "NODAT Training", seconds: 8, source: "youtube" },
  shamgod:               { videoId: "BmTh9Wqz1dc", title: "Crazy New Ball Handling Drill! Drill To Help Your Shamgod Move!", channel: "ILoveBasketballTV", seconds: 58, source: "youtube", trusted: true },
  snatch:                { videoId: "NTS_8LFX9No", title: "5 Snatch Back Moves! Which Is The Best?", channel: "ILoveBasketballTV", seconds: 25, source: "youtube", trusted: true },
  spin:                  { videoId: "R-NdxJLMPLw", title: "4 Drills For A Nasty Spin Move (Beginners & Advanced)", channel: "Get Handles Basketball", seconds: 31, source: "youtube", trusted: true },
  stutter:               { videoId: "mLlGsR0LTrw", title: "👟FULL COURT STUTTER SERIES👟 | Elite Ball Handling & Footwork", channel: "Hoop Dreams Basketball 🏀🧠", seconds: 12, source: "youtube" },

  // ── passing ──
  bounce:                { videoId: "Guig8aK0DxU", title: "Bounce Passing Drill", channel: "STACK Basketball Training", seconds: 14, source: "youtube" },
  chest:                 { videoId: "kc_ZRvrsAZ0", title: "Chest passing | Throwing & catching (grade K-3) › Teaching Fundamentals of PE", channel: "Prime Coaching Sport", seconds: 46, source: "youtube" },
  kick_out:              { videoId: "Vkhw9_dSrqg", title: "Kick Out Pass", channel: "OTRP Teaching Library", seconds: 50, source: "youtube" },
  outlet:                { videoId: "v--ztyHtEeY", title: "Outlet Basketball Drill", channel: "Bryson Walrup", seconds: 19, source: "youtube" },
  pocket:                { videoId: "fbep5jy3X6I", title: "Perfect Your Pocket Pass!", channel: "Ryan Razooky (R2BBALL)", seconds: 13, source: "youtube" },
  skip:                  { videoId: "yL6eTCaedd8", title: "Skip Pass Drill", channel: "STACK Basketball Training", seconds: 24, source: "youtube" },

  // ── rebounding ──
  reb_outlet:            { videoId: "RMwR7WHOPCk", title: "Defensive Drill for Youth Basketball   Rebound  Outlet  Lay Up by George Karl", channel: "R Govind", seconds: 89, source: "youtube" },
  reb_putback:           { videoId: "zrkTBdHFmgs", title: "Rebound & Put Back Drill", channel: "Junior Wildcats Basketball", seconds: 14, source: "youtube" },

  // ── shooting ──
  catch_shoot:           { videoId: "ow16151mQDE", title: "CATCH and SHOOT Drill for Shooting Footwork 👣", channel: "ILoveBasketballTV", seconds: 10, source: "youtube", trusted: true },
  curl:                  { videoId: "A1nHvxugFtk", title: "Basketball Drill: Partner Curl Shooting", channel: "NODAT Training", seconds: 30, source: "youtube" },
  dho_entry:             { videoId: "yLccPEHr_ow", title: "Basketball Shooting Machine Drills: DHO Drift Kick Back", channel: "Dr. Dish Basketball", seconds: 88, source: "youtube" },
  drift:                 { videoId: "HlvtGoh340w", title: "Alabama Basketball Shooting Drill - Baseline Drift off a Penetrate and Kick (on The Gun 10K)", channel: "Shoot-A-Way", seconds: 88, source: "youtube", trusted: true },
  flare:                 { videoId: "CTgJrWytk_0", title: "1v1 Flare Shooting Drill", channel: "Coach Tony Miller", seconds: 5, source: "youtube" },
  floater:               { videoId: "UR16q3SMUtY", title: "Improve your floater 👀", channel: "HoopStudy", seconds: 9, source: "youtube", trusted: true },
  pullup_1:              { videoId: "6D9QJDf0D4E", title: "SIMPLE DRILL FOR PERFECT DRIBBLE PULL UPS #basketballtraining", channel: "Keith Poitier Performance", seconds: 25, source: "youtube" },
  pin_down:              { videoId: "vZrEGrzroYE", title: "UNC Basketball Shooting Drill - Pin Down with Dribble Hand-Off with The Gun", channel: "Shoot-A-Way", seconds: 69, source: "youtube", trusted: true },
  reject_screen:         { videoId: "MzBk9-S3HT4", title: "When REFUSING the screen into OPEN SPACE, try this PUSH OUT!", channel: "HoopStudy", seconds: 16, source: "youtube", trusted: true },
  relocation:            { videoId: "8FNOxKUO2ec", title: "CATCH AND SHOOT AFTER RELOCATION DRILL!!!!", channel: "HoopStudy", seconds: 23, source: "youtube", trusted: true },
  side_step:             { videoId: "Tu_QirrOKmk", title: "You NEED both types of SHOOTING FOOTWORK", channel: "HoopStudy", seconds: 14, source: "youtube", trusted: true },
  spot_up:               { videoId: "h4T9ccaFCpk", title: "Add this 3 spot FOOT REPLACEMENT CATCH & SHOOT drill to your PRESEASON workouts!!!!", channel: "HoopStudy", seconds: 15, source: "youtube", trusted: true },
  transition_shot:       { videoId: "dqOlxbOU_jM", title: "ONE ON ONE SHOOTING DRILL FOR YOUR PRESEASON WORK!!!!", channel: "HoopStudy", seconds: 26, source: "youtube", trusted: true },
  step_back:             { videoId: "iOn_I4Nd2Y4", title: "Basketball Drill - Step Back Hesitation shooting drill on The Gun", channel: "Shoot-A-Way", seconds: 58, source: "youtube", trusted: true },
  pullup_2:              { videoId: "6qTUj818flI", title: "Develop a SMOOTH Pull-Up Jumper After Doing This Drill 🏀", channel: "ILoveBasketballTV", seconds: 31, source: "youtube", trusted: true },
  zoom:                  { videoId: "zQWSVtc_9ds", title: "Zoom action in high school basketball #basketballcoach #highschoolbasketball #bball #hoops #zoom", channel: "Matt Hackenberg", seconds: 15, source: "youtube" },
};

/** Convenience: does a skill have a curated video? */
export const hasSkillVideo = (skillId) => Boolean(SKILL_VIDEOS[skillId]);
